--- #YAML:1.0
name: IO-Infiles
version: 0.03
author:
  - Ioannis Tambouras <ioannis@yahoo.com>
abstract: Multiple handlers for multiple __END__-like tokens
license: perl
requires:
  perl: 5.6
recommends:
  Test::Distribution: 1.22
  Test::Pod: 1.20
  Test::Pod::Coverage: 1.06
provides:
  IO::Infiles:
    file: lib/IO/Infiles.pm
    version: 0.03
generated_by: Module::Build version 0.2611
