---
name: IO-Infiles
version: 0.04
author:
  - 'Ioannis Tambouras <ioannis@yahoo.com>'
abstract: Multiple handlers for multiple __END__-like tokens
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.006
recommends:
  Test::Distribution: 1.22
  Test::Pod: 1.20
  Test::Pod::Coverage: 1.06
provides:
  IO::Infiles:
    file: lib/IO/Infiles.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
